//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace QuotesWeb.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QuotationsContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QuotationsContainer object using the connection string found in the 'QuotationsContainer' section of the application configuration file.
        /// </summary>
        public QuotationsContainer() : base("name=QuotationsContainer", "QuotationsContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuotationsContainer object.
        /// </summary>
        public QuotationsContainer(string connectionString) : base(connectionString, "QuotationsContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuotationsContainer object.
        /// </summary>
        public QuotationsContainer(EntityConnection connection) : base(connection, "QuotationsContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Quotation> Quotations
        {
            get
            {
                if ((_Quotations == null))
                {
                    _Quotations = base.CreateObjectSet<Quotation>("Quotations");
                }
                return _Quotations;
            }
        }
        private ObjectSet<Quotation> _Quotations;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Quotations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuotations(Quotation quotation)
        {
            base.AddObject("Quotations", quotation);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Quotations", Name="Quotation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Quotation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Quotation object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="quote">Initial value of the Quote property.</param>
        /// <param name="lastUpdated">Initial value of the LastUpdated property.</param>
        public static Quotation CreateQuotation(global::System.Int32 id, global::System.String quote, global::System.DateTime lastUpdated)
        {
            Quotation quotation = new Quotation();
            quotation.Id = id;
            quotation.Quote = quote;
            quotation.LastUpdated = lastUpdated;
            return quotation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Quote
        {
            get
            {
                return _Quote;
            }
            set
            {
                OnQuoteChanging(value);
                ReportPropertyChanging("Quote");
                _Quote = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Quote");
                OnQuoteChanged();
            }
        }
        private global::System.String _Quote;
        partial void OnQuoteChanging(global::System.String value);
        partial void OnQuoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.String _Author = "Unknown";
        partial void OnAuthorChanging(global::System.String value);
        partial void OnAuthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String When
        {
            get
            {
                return _When;
            }
            set
            {
                OnWhenChanging(value);
                ReportPropertyChanging("When");
                _When = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("When");
                OnWhenChanged();
            }
        }
        private global::System.String _When;
        partial void OnWhenChanging(global::System.String value);
        partial void OnWhenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private global::System.DateTime _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.DateTime value);
        partial void OnLastUpdatedChanged();

        #endregion
    
    }

    #endregion
    
}
